# Numpy
   * Numarical python/numaric python
   * NumPy is a programing language that deals with multi-dimensional arrays/matrices
   * NumPy supports a large number of mathamatical operations
# why use of NumPy
     * escapecially for matrix multiplication and reshaping
     * on
     
# how to install NumPy
     * it was installed by default in anaconda
   
   
   
   
   * 

In [2]:
import numpy as np



In [3]:
print(np.__version__)

1.19.2


In [6]:
# arrays
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [5]:
print(np.array([2,4,6,8]))

[2 4 6 8]


In [12]:
# two d
data=np.array([[1,2,3,4],[5,6,7,8]])
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
#mathamatical operations
a1=np.array([3,5,7,9])
a2=np.array([2,4,6,8])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1%a2)

[ 5  9 13 17]
[1 1 1 1]
[ 6 20 42 72]
[1.5        1.25       1.16666667 1.125     ]
[1 1 1 1]


In [17]:
#shape of an array*(int)
data=np.array([[1,2,3,4],[5,6,7,8]])
print(np.shape(data))
print(data.dtype)

(2, 4)
int32


In [21]:
#shape of an array*(float)
data1=np.array([[1.0,2.0,3.0],[2.5,3.6,5.8]])
print(np.shape(data1))
print(data1.dtype)

(2, 3)
float64


In [24]:
#numpy 0's & 1's
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [25]:
np.zeros((3,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [29]:
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
# numpy reshape
data2=np.array([[1,2,3,4],[6,7,8,9]])
print(data2)
data2.reshape((4,2))

[[1 2 3 4]
 [6 7 8 9]]


array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [38]:
#numpy flatten
print(data2)
data2.flatten()

[[1 2 3 4]
 [6 7 8 9]]


array([1, 2, 3, 4, 6, 7, 8, 9])

In [39]:
#numpy hstack(data open horizantal)
print(a1)
print(a2)
np.hstack((a1,a2))

[3 5 7 9]
[2 4 6 8]


array([3, 5, 7, 9, 2, 4, 6, 8])

In [40]:
#numpy vstack(data open vertical)
print(a1)
print(a2)
np.vstack((a1,a2))

[3 5 7 9]
[2 4 6 8]


array([[3, 5, 7, 9],
       [2, 4, 6, 8]])

In [44]:
#numpy vstack(data open vertical with single value)
#print(a1)
print(a2)
np.vstack((a2))

[2 4 6 8]


array([[2],
       [4],
       [6],
       [8]])

In [45]:
data2

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [52]:
#to calculate mean
print(data2)
print(data2.mean())
print(np.median(data2))
print(np.mod(2,3))

[[1 2 3 4]
 [6 7 8 9]]
5.0
5.0
2


In [47]:
#to calculate standard deviation
print(data2)
data2.std()

[[1 2 3 4]
 [6 7 8 9]]


2.7386127875258306

In [55]:
#generate random numbers
d=np.random.randint(1,30,(3,3))
d

array([[ 8, 29, 26],
       [27, 17,  7],
       [21, 10, 28]])

In [56]:
#random normalloc(mean),scale(medium)
np.random.normal(5,4,10)

array([ 9.82153385,  9.34546657,  6.58334617, 11.78409729,  9.37264512,
       -2.48880994,  2.1090582 ,  6.49657798, -1.26592119,  0.74757612])

In [61]:
#numpy stastical function(min,max,mean,std)
print(d)
print(d.min())
print(d.max())
print(d.std())

[[ 8 29 26]
 [27 17  7]
 [21 10 28]]
7
29
8.48237097066325


In [63]:
#transpose
print(d)
d.T

[[ 8 29 26]
 [27 17  7]
 [21 10 28]]


array([[ 8, 27, 21],
       [29, 17, 10],
       [26,  7, 28]])

In [68]:
#identity matrix
print(np.eye(5,dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [69]:
#dot method
print(a1)
print(a2)
a1.dot(a2)

[3 5 7 9]
[2 4 6 8]


140

In [72]:
d1=np.array([1,2,3,4])
np.array([d1,pow(d1,2)])

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [76]:
#repeate
a=np.repeat([1,2,3,4],3)
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [81]:
#arrange function
#syn:- arrange(start,stop,step)
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [ ]:
# numpy linspace(default=50)
#syn:- linspace(start,stop,number,endpoint)


In [ ]:
x=np.array([1,2,3],[4,5,6])